name: main
on:
  - push
  - workflow_dispatch
  
  
jobs:

  end-to-end-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: cd CRC_Terraform/end-to-end-test && npm install && node index.js
      
  build-and-deploy:
    needs: end-to-end-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - run: terraform init
        working-directory: CRC_Terraform
      - run: terraform fmt
        working-directory: CRC_Terraform
      - run: terraform validate
        working-directory: CRC_Terraform
      - run: terraform plan
        working-directory: CRC_Terraform
      - run: terraform apply
        working-directory: CRC_Terraform


  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: CRC_Terraform/website-resources
